{
  "formatVersion": "1.1",
  "component": {
    "group": "com.overFTCLib.ftc",
    "module": "overFTCLib-java",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "overFTCLib-java-0.0.7.jar",
          "url": "overFTCLib-java-0.0.7.jar",
          "size": 1782,
          "sha512": "ce7d47e8daf3dd6a0f7c3f2641906763c8cf108441edd21eaf2a378860a6bfe7a0ae3682b00da11098b3ae4aa8eea4731bdac0be5a58b7ca20d0f39115e127e8",
          "sha256": "c02924fc70eb483b82d8554cf53896a2953daf2f39ce58825e3d1ff6d64b2380",
          "sha1": "53f2358e1704d3c3d51176f490c6f2e8ebf0d479",
          "md5": "a0076d2ca94b46810780d537a475d37a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2024.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "overFTCLib-java-0.0.7.jar",
          "url": "overFTCLib-java-0.0.7.jar",
          "size": 1782,
          "sha512": "ce7d47e8daf3dd6a0f7c3f2641906763c8cf108441edd21eaf2a378860a6bfe7a0ae3682b00da11098b3ae4aa8eea4731bdac0be5a58b7ca20d0f39115e127e8",
          "sha256": "c02924fc70eb483b82d8554cf53896a2953daf2f39ce58825e3d1ff6d64b2380",
          "sha1": "53f2358e1704d3c3d51176f490c6f2e8ebf0d479",
          "md5": "a0076d2ca94b46810780d537a475d37a"
        }
      ]
    }
  ]
}
