{
  "formatVersion": "1.1",
  "component": {
    "group": "com.overFTCLib.ftc",
    "module": "overFTCLib-java",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2024.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "overFTCLib-java-0.1.jar",
          "url": "overFTCLib-java-0.1.jar",
          "size": 13675,
          "sha512": "00909b225a93156fbf9a3427e10d24319eee62c94c4dd8f861050df857e84ea9b97759332b9d3e8d7265a9c8d5a5b2cfda4cc20bccc1f4dcffb7580d106cb162",
          "sha256": "3faf286764fbbefd8113a9513f388167fa41bdc135da80bf6b7d191394548d51",
          "sha1": "8070d0bba80ec0fddff90a6dcf73b02878f21cde",
          "md5": "c6d5d194815a4b717bc59a9453b575d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2024.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2024.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "overFTCLib-java-0.1.jar",
          "url": "overFTCLib-java-0.1.jar",
          "size": 13675,
          "sha512": "00909b225a93156fbf9a3427e10d24319eee62c94c4dd8f861050df857e84ea9b97759332b9d3e8d7265a9c8d5a5b2cfda4cc20bccc1f4dcffb7580d106cb162",
          "sha256": "3faf286764fbbefd8113a9513f388167fa41bdc135da80bf6b7d191394548d51",
          "sha1": "8070d0bba80ec0fddff90a6dcf73b02878f21cde",
          "md5": "c6d5d194815a4b717bc59a9453b575d6"
        }
      ]
    }
  ]
}
