{
  "formatVersion": "1.1",
  "component": {
    "group": "com.overFTCLib.ftc",
    "module": "overFTCLib-java",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "overFTCLib-java-0.0.6.jar",
          "url": "overFTCLib-java-0.0.6.jar",
          "size": 1784,
          "sha512": "21de948ce3533ccdf498fb979e62ca107c34f359e3a813e8318ab085be3bb26b7a2152fe17111594408f328cc8f0dff3df30932722a287adfe6b6ba00e1820cb",
          "sha256": "f3ede42c01652d683a53f6df8dd4e43625ac7dde36dfa087aa7fb8e4a5f059e4",
          "sha1": "99a01a09cdfb338cb5a43572adce96392966c682",
          "md5": "a5bd3bbb111d158d5ca0836001404e7d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "overFTCLib-java-0.0.6.jar",
          "url": "overFTCLib-java-0.0.6.jar",
          "size": 1784,
          "sha512": "21de948ce3533ccdf498fb979e62ca107c34f359e3a813e8318ab085be3bb26b7a2152fe17111594408f328cc8f0dff3df30932722a287adfe6b6ba00e1820cb",
          "sha256": "f3ede42c01652d683a53f6df8dd4e43625ac7dde36dfa087aa7fb8e4a5f059e4",
          "sha1": "99a01a09cdfb338cb5a43572adce96392966c682",
          "md5": "a5bd3bbb111d158d5ca0836001404e7d"
        }
      ]
    }
  ]
}
